library 'jenkins-shared-library-example'

@Library('jenkins-shared-library-example')
import org.somecompany.build.ClosureParameters
//@Library('jenkins-shared-library-example')
import org.somecompany.build.SomeFlag

pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                ex_msbuild 'some/path/to.sln', SomeFlag.Three
                ex_msbuild 'some/path/to.sln', SomeFlag.Two, false
                ex_msbuild 'some/path/to.sln', SomeFlag.One, true
                //String solutionPath, SomeFlag someFlag,  boolean strict = true
                ex_msbuild strict: true, someFlag: SomeFlag.Two, solutionPath: '/my/way'
            }
        }
        stage('step with closure') {
            steps{
                stepWithClosure('hello') { String first, String second ->
                    echo first
                    echo second
                }
                stepWithClosure('hello') {
                    echo 'parameters can be ignored if they are not needed'
                }
                stepWithClosure('hello') { Map map ->
                    echo 'can not convert parameters to a map, this will just echo the first argument'
                    echo map
                }
                stepWithClosureExplicitParameterObject('world'){ ClosureParameters parameters ->
                    echo 'different approach to argument passing in a closure'
                    echo parameters.parenthesis
                    echo parameters.squareBracket
                }
            }
        }

    }
}
